
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              value: {{ .Values.database.user }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password }}
            - name: DB_NAME
              value: {{ .Values.database.name }}
          ports:
            - containerPort: 3000
            - containerPort: 9464
